Repository AY2122S1-CS2103T-T15-1/tp, pull requests merged in 2021-10, with the labels that each got.

#103 Create suggestions
  build.gradle
  src/main/java/gomedic/commons/core/Messages.java
  src/main/java/gomedic/logic/parser/AddressBookParser.java
  src/main/java/gomedic/ui/MainWindow.java
  src/test/java/gomedic/commons/core/MessagesTest.java
  src/test/java/gomedic/logic/LogicManagerTest.java
  src/test/java/gomedic/logic/parser/AddressBookParserTest.java
Labels: type.Enhancement, hacktoberfest-accepted

#105 Lauwsj/activity storage
  src/main/java/gomedic/MainApp.java
  src/main/java/gomedic/logic/Logic.java
  src/main/java/gomedic/logic/LogicManager.java
  src/main/java/gomedic/model/Model.java
  src/main/java/gomedic/model/ModelManager.java
  src/main/java/gomedic/model/ReadOnlyUserPrefs.java
  src/main/java/gomedic/model/UserPrefs.java
  src/main/java/gomedic/model/activity/ActivityId.java
  src/main/java/gomedic/model/activity/Description.java
  src/main/java/gomedic/model/activity/Title.java
  src/main/java/gomedic/model/commonfield/Id.java
  src/main/java/gomedic/storage/AddressBookStorage.java
  src/main/java/gomedic/storage/JsonAdaptedActivity.java
  src/main/java/gomedic/storage/JsonAddressBookStorage.java
  src/main/java/gomedic/storage/JsonSerializableAddressBook.java
  src/main/java/gomedic/storage/Storage.java
  src/main/java/gomedic/storage/StorageManager.java
  src/main/java/gomedic/ui/MainWindow.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/conflictingActivitiesAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateActivitiesAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidActivityAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/gomedic/logic/commands/AddCommandTest.java
  src/test/java/gomedic/model/ModelManagerTest.java
  src/test/java/gomedic/model/UserPrefsTest.java
  src/test/java/gomedic/model/activity/ActivityIdTest.java
  src/test/java/gomedic/model/activity/DescriptionTest.java
  src/test/java/gomedic/model/activity/TitleTest.java
  src/test/java/gomedic/model/activity/UniqueActivityListTest.java
  src/test/java/gomedic/model/commonfield/IdTest.java
  src/test/java/gomedic/storage/JsonAddressBookStorageTest.java
  src/test/java/gomedic/storage/JsonSerializableAddressBookTest.java
  src/test/java/gomedic/storage/JsonUserPrefsStorageTest.java
  src/test/java/gomedic/storage/StorageManagerTest.java
  src/test/java/gomedic/testutil/TypicalActivities.java
  src/test/java/gomedic/testutil/TypicalPersons.java
Labels: hacktoberfest-accepted

#111 Create basic Patient model except Description Class
  src/main/java/gomedic/model/person/patient/Age.java
  src/main/java/gomedic/model/person/patient/BloodType.java
  src/main/java/gomedic/model/person/patient/Gender.java
  src/main/java/gomedic/model/person/patient/Height.java
  src/main/java/gomedic/model/person/patient/Patient.java
  src/main/java/gomedic/model/person/patient/PatientId.java
  src/main/java/gomedic/model/person/patient/Weight.java
  src/test/java/gomedic/model/person/patient/AgeTest.java
  src/test/java/gomedic/model/person/patient/BloodTypeTest.java
  src/test/java/gomedic/model/person/patient/GenderTest.java
  src/test/java/gomedic/model/person/patient/HeightTest.java
  src/test/java/gomedic/model/person/patient/PatientIdTest.java
  src/test/java/gomedic/model/person/patient/PatientTest.java
  src/test/java/gomedic/model/person/patient/WeightTest.java
  src/test/java/gomedic/testutil/modelbuilder/PatientBuilder.java
Labels: hacktoberfest-accepted

#117 Create storage related functions and tests for Doctor
  src/main/java/gomedic/model/AddressBook.java
  src/main/java/gomedic/model/ReadOnlyAddressBook.java
  src/main/java/gomedic/model/person/UniqueAbstractPersonList.java
  src/main/java/gomedic/model/person/doctor/DoctorId.java
  src/main/java/gomedic/storage/JsonAdaptedDoctor.java
  src/main/java/gomedic/storage/JsonSerializableAddressBook.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidDoctorAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidDoctorAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/conflictingActivitiesAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateActivitiesAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateDoctorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidActivityAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidDoctorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/gomedic/model/AddressBookTest.java
  src/test/java/gomedic/model/person/UniqueAbstractPersonListTest.java
  src/test/java/gomedic/model/person/doctor/DoctorIdTest.java
  src/test/java/gomedic/storage/JsonAdaptedDoctorTest.java
  src/test/java/gomedic/storage/JsonAddressBookStorageTest.java
  src/test/java/gomedic/storage/JsonSerializableAddressBookTest.java
  src/test/java/gomedic/testutil/TypicalPersons.java
Labels: hacktoberfest-accepted

#118 Lauwsj/add activity command
  docs/UserGuide.md
  src/main/java/gomedic/commons/core/Messages.java
  src/main/java/gomedic/logic/Logic.java
  src/main/java/gomedic/logic/LogicManager.java
  src/main/java/gomedic/logic/commands/EditCommand.java
  src/main/java/gomedic/logic/commands/ListCommand.java
  src/main/java/gomedic/logic/commands/addcommand/AddActivityCommand.java
  src/main/java/gomedic/logic/parser/AddressBookParser.java
  src/main/java/gomedic/logic/parser/CliSyntax.java
  src/main/java/gomedic/logic/parser/ParserUtil.java
  src/main/java/gomedic/logic/parser/addcommandparser/AddActivityCommandParser.java
  src/main/java/gomedic/logic/parser/addcommandparser/AddPersonCommandParser.java
  src/main/java/gomedic/model/AddressBook.java
  src/main/java/gomedic/model/Model.java
  src/main/java/gomedic/model/ModelManager.java
  src/main/java/gomedic/model/activity/Description.java
  src/main/java/gomedic/model/activity/Title.java
  src/main/java/gomedic/model/activity/UniqueActivityList.java
  src/main/java/gomedic/model/commonfield/Id.java
  src/test/java/gomedic/logic/LogicManagerTest.java
  src/test/java/gomedic/logic/commands/CommandTestUtil.java
  src/test/java/gomedic/logic/commands/addcommand/AddActivityCommandTest.java
  src/test/java/gomedic/logic/commands/addcommand/AddActivityIntegrationTest.java
  src/test/java/gomedic/logic/commands/addcommand/AddPersonCommandIntegrationTest.java
  src/test/java/gomedic/logic/commands/addcommand/AddPersonCommandTest.java
  src/test/java/gomedic/logic/parser/AddressBookParserTest.java
  src/test/java/gomedic/logic/parser/ParserUtilTest.java
  src/test/java/gomedic/logic/parser/addcommandparser/AddActivityParserTest.java
  src/test/java/gomedic/logic/parser/addcommandparser/AddCommandParserTest.java
  src/test/java/gomedic/model/AddressBookTest.java
  src/test/java/gomedic/model/ModelManagerTest.java
  src/test/java/gomedic/model/activity/UniqueActivityListTest.java
  src/test/java/gomedic/model/commonfield/IdTest.java
  src/test/java/gomedic/testutil/AddressBookBuilder.java
  src/test/java/gomedic/testutil/PersonUtil.java
  src/test/java/gomedic/testutil/TypicalActivities.java
  src/test/java/gomedic/testutil/modelbuilder/ActivityBuilder.java
Labels: hacktoberfest-accepted

#119 Add feedback box to Ui
  docs/images/Ui-activity.png
  docs/images/Ui-doctor.png
  docs/images/Ui-one-doctor.png
  docs/images/Ui-one-patient.png
  docs/images/Ui.png
Labels: priority.high, hacktoberfest-accepted

#124 Finish creating storage related functions and tests for Patient
  src/main/java/gomedic/model/AddressBook.java
  src/main/java/gomedic/model/ReadOnlyAddressBook.java
  src/main/java/gomedic/model/person/patient/PatientId.java
  src/main/java/gomedic/storage/JsonAdaptedPatient.java
  src/main/java/gomedic/storage/JsonSerializableAddressBook.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidDoctorAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPatientAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidDoctorAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPatientAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/conflictingActivitiesAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateActivitiesAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateDoctorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePatientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidActivityAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidDoctorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPatientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/gomedic/model/AddressBookTest.java
  src/test/java/gomedic/model/person/patient/PatientIdTest.java
  src/test/java/gomedic/storage/JsonAdaptedPatientTest.java
  src/test/java/gomedic/storage/JsonAddressBookStorageTest.java
  src/test/java/gomedic/storage/JsonSerializableAddressBookTest.java
  src/test/java/gomedic/testutil/TypicalPersons.java
Labels: hacktoberfest-accepted

#125 Finish patient add command
  src/main/java/gomedic/logic/Logic.java
  src/main/java/gomedic/logic/LogicManager.java
  src/main/java/gomedic/logic/commands/addcommand/AddPatientCommand.java
  src/main/java/gomedic/logic/parser/AddressBookParser.java
  src/main/java/gomedic/logic/parser/CliSyntax.java
  src/main/java/gomedic/logic/parser/ParserUtil.java
  src/main/java/gomedic/logic/parser/addcommandparser/AddPatientCommandParser.java
  src/main/java/gomedic/model/AddressBook.java
  src/main/java/gomedic/model/Model.java
  src/main/java/gomedic/model/ModelManager.java
  src/test/java/gomedic/logic/LogicManagerTest.java
  src/test/java/gomedic/logic/commands/CommandTestUtil.java
  src/test/java/gomedic/logic/commands/addcommand/AddPatientCommandTest.java
  src/test/java/gomedic/logic/commands/addcommand/AddPatientIntegrationTest.java
  src/test/java/gomedic/logic/parser/ParserUtilTest.java
  src/test/java/gomedic/logic/parser/addcommandparser/AddPatientParserTest.java
  src/test/java/gomedic/model/AddressBookTest.java
  src/test/java/gomedic/model/ModelManagerTest.java
  src/test/java/gomedic/testutil/AddressBookBuilder.java
  src/test/java/gomedic/testutil/TypicalPersons.java
  src/test/java/gomedic/testutil/modelbuilder/PatientBuilder.java
Labels: hacktoberfest-accepted

#128 Finish patient list command
  src/main/java/gomedic/logic/commands/listcommand/ListPatientCommand.java
  src/main/java/gomedic/logic/parser/AddressBookParser.java
  src/main/java/gomedic/model/AddressBook.java
  src/main/java/gomedic/model/Model.java
  src/main/java/gomedic/model/ModelManager.java
  src/main/java/gomedic/model/ReadOnlyAddressBook.java
  src/main/java/gomedic/model/person/UniqueAbstractPersonList.java
  src/main/java/gomedic/storage/JsonSerializableAddressBook.java
  src/main/java/gomedic/ui/MainWindow.java
  src/main/java/gomedic/ui/card/PatientCard.java
  src/main/java/gomedic/ui/panel/PatientListPanel.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/PatientListPanel.fxml
  src/test/java/gomedic/logic/commands/CommandTestUtil.java
  src/test/java/gomedic/logic/commands/listcommand/ListPatientCommandTest.java
  src/test/java/gomedic/logic/parser/AddressBookParserTest.java
  src/test/java/gomedic/model/AddressBookTest.java
Labels: hacktoberfest-accepted

#132 Lauwsj/delete activity
  src/main/java/gomedic/commons/core/Messages.java
  src/main/java/gomedic/logic/commands/deletecommand/DeleteActivityCommand.java
  src/main/java/gomedic/logic/commands/deletecommand/DeletePersonCommand.java
  src/main/java/gomedic/logic/parser/AddressBookParser.java
  src/main/java/gomedic/logic/parser/ParserUtil.java
  src/main/java/gomedic/logic/parser/deletecommandparser/DeleteActivityParser.java
  src/main/java/gomedic/logic/parser/deletecommandparser/DeleteCommandParser.java
  src/main/java/gomedic/model/Model.java
  src/main/java/gomedic/model/ModelManager.java
  src/main/resources/view/ActivityListPanel.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/gomedic/logic/LogicManagerTest.java
  src/test/java/gomedic/logic/commands/CommandTestUtil.java
  src/test/java/gomedic/logic/commands/deletecommand/DeleteActivityCommandTest.java
  src/test/java/gomedic/logic/commands/deletecommand/DeletePersonCommandTest.java
  src/test/java/gomedic/logic/parser/AddressBookParserTest.java
  src/test/java/gomedic/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/gomedic/logic/parser/ParserUtilTest.java
  src/test/java/gomedic/storage/JsonAdaptedActivityTest.java
Labels: hacktoberfest-accepted

#133 Finish delete patient command
  src/main/java/gomedic/commons/core/Messages.java
  src/main/java/gomedic/logic/commands/deletecommand/DeleteActivityCommand.java
  src/main/java/gomedic/logic/commands/deletecommand/DeletePatientCommand.java
  src/main/java/gomedic/logic/parser/AddressBookParser.java
  src/main/java/gomedic/logic/parser/deletecommandparser/DeletePatientParser.java
  src/main/java/gomedic/model/Model.java
  src/main/java/gomedic/model/ModelManager.java
  src/test/java/gomedic/logic/LogicManagerTest.java
  src/test/java/gomedic/logic/commands/CommandTestUtil.java
  src/test/java/gomedic/logic/commands/deletecommand/DeletePatientCommandTest.java
Labels: hacktoberfest-accepted

#142 Add author tag to datetime parser in Time class
  src/main/java/gomedic/model/commonfield/Time.java
Labels: hacktoberfest-accepted

#144 Patient update command
  docs/UserGuide.md
  src/main/java/gomedic/logic/commands/editcommand/EditPatientCommand.java
  src/main/java/gomedic/logic/parser/AddressBookParser.java
  src/main/java/gomedic/logic/parser/editcommandparser/EditPatientCommandParser.java
  src/main/java/gomedic/model/Model.java
  src/main/java/gomedic/model/ModelManager.java
  src/main/java/gomedic/model/person/patient/Patient.java
  src/test/java/gomedic/logic/commands/CommandTestUtil.java
  src/test/java/gomedic/logic/commands/editcommand/EditPatientCommandTest.java
  src/test/java/gomedic/logic/commands/editcommand/EditPatientDescriptorTest.java
  src/test/java/gomedic/logic/parser/editcommandparser/EditPatientCommandParserTest.java
  src/test/java/gomedic/testutil/TypicalPersons.java
  src/test/java/gomedic/testutil/editdescriptorbuilder/EditPatientDescriptorBuilder.java
Labels: hacktoberfest-accepted

#153 Finish the skin for input, feedback and scrollbar
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: hacktoberfest-accepted

#154 Add sorting by start time and show within certain period for activities
  src/main/java/gomedic/logic/Logic.java
  src/main/java/gomedic/logic/LogicManager.java
  src/main/java/gomedic/logic/commands/addcommand/AddActivityCommand.java
  src/main/java/gomedic/logic/commands/deletecommand/DeleteActivityCommand.java
  src/main/java/gomedic/logic/commands/editcommand/EditActivityCommand.java
  src/main/java/gomedic/logic/commands/listcommand/ListActivityCommand.java
  src/main/java/gomedic/logic/parser/AddressBookParser.java
  src/main/java/gomedic/logic/parser/CliSyntax.java
  src/main/java/gomedic/logic/parser/ParserUtil.java
  src/main/java/gomedic/logic/parser/listcommandparser/ListActivityParser.java
  src/main/java/gomedic/model/AddressBook.java
  src/main/java/gomedic/model/Model.java
  src/main/java/gomedic/model/ModelItem.java
  src/main/java/gomedic/model/ModelManager.java
  src/main/java/gomedic/model/ReadOnlyAddressBook.java
  src/main/java/gomedic/ui/MainWindow.java
  src/test/java/gomedic/logic/LogicManagerTest.java
  src/test/java/gomedic/logic/commands/CommandTestUtil.java
  src/test/java/gomedic/logic/commands/deletecommand/DeleteActivityCommandTest.java
  src/test/java/gomedic/logic/commands/editcommand/EditActivityCommandTest.java
  src/test/java/gomedic/logic/commands/listcommand/ListActivityCommandTest.java
  src/test/java/gomedic/logic/parser/ParserUtilTest.java
  src/test/java/gomedic/logic/parser/listcommandparser/ListActivityParserTest.java
  src/test/java/gomedic/model/AddressBookTest.java
  src/test/java/gomedic/model/ModelManagerTest.java
Labels: type.Enhancement, hacktoberfest-accepted

#145 Finetune and bug fix suggestions feature
  src/main/java/gomedic/commons/core/Messages.java
  src/test/java/gomedic/commons/core/MessagesTest.java
Labels: hacktoberfest-accepted

#169 Lauwsj/integrate profile
  src/main/java/gomedic/logic/commands/ReferralCommand.java
  src/main/java/gomedic/logic/commands/addcommand/AddAppointmentCommand.java
  src/main/java/gomedic/model/person/patient/Patient.java
  src/main/java/gomedic/ui/card/ActivityCard.java
  src/main/java/gomedic/ui/table/ActivityTable.java
  src/main/java/gomedic/ui/view/PatientView.java
  src/main/resources/view/PatientView.fxml
  src/test/java/gomedic/model/person/patient/PatientTest.java
  src/test/java/gomedic/storage/JsonAddressBookStorageTest.java
  src/test/java/gomedic/storage/JsonSerializableAddressBookTest.java
Labels: hacktoberfest-accepted

#176 Add sample documentation for suggestions implementation
  docs/DeveloperGuide.md
  docs/diagrams/SuggestionsSequenceDiagram.puml
  docs/images/SuggestionsSequenceDiagram.png
  src/main/java/gomedic/commons/core/Messages.java
Labels: hacktoberfest-accepted

#178 Update DG with profile command implementation
  docs/DeveloperGuide.md
  docs/diagrams/ProfileSequenceDiagram.puml
  docs/images/ProfileSequenceDiagram.png
Labels: hacktoberfest-accepted

#251 Bug fix
  docs/UserGuide.md
  src/main/java/gomedic/logic/commands/addcommand/AddPatientCommand.java
  src/main/java/gomedic/logic/commands/editcommand/EditPatientCommand.java
  src/main/java/gomedic/model/commonfield/Phone.java
  src/main/java/gomedic/model/person/patient/Age.java
  src/main/java/gomedic/model/person/patient/BloodType.java
  src/main/java/gomedic/model/person/patient/Gender.java
  src/main/java/gomedic/model/person/patient/Height.java
  src/main/java/gomedic/model/person/patient/Weight.java
  src/main/java/gomedic/model/util/SampleDataUtil.java
  src/main/java/gomedic/ui/view/PatientView.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPatientAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPatientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateDoctorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePatientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidDoctorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPatientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/gomedic/logic/commands/CommandTestUtil.java
  src/test/java/gomedic/logic/commands/addcommand/AddDoctorIntegrationTest.java
  src/test/java/gomedic/logic/commands/addcommand/AddPatientIntegrationTest.java
  src/test/java/gomedic/logic/commands/editcommand/EditPatientCommandTest.java
  src/test/java/gomedic/logic/parser/ParserUtilTest.java
  src/test/java/gomedic/model/commonfield/PhoneTest.java
  src/test/java/gomedic/model/person/doctor/DoctorTest.java
  src/test/java/gomedic/model/person/patient/BloodTypeTest.java
  src/test/java/gomedic/model/person/patient/PatientTest.java
  src/test/java/gomedic/model/util/BloodTypeContainsKeywordsPredicateTest.java
  src/test/java/gomedic/testutil/TypicalPersons.java
  src/test/java/gomedic/testutil/modelbuilder/PatientBuilder.java
Labels: hacktoberfest-accepted

#260 Lauwsj/table bug
  src/main/resources/view/LightTheme.css
Labels: type.Enhancement

#257 Lauwsj/ug bug
  docs/UserGuide.md
  docs/images/navigate/navigation1.png
  docs/images/navigate/navigation2.png
  docs/images/navigate/navigation3.png
  docs/images/ui/segmentation.png
  src/main/java/gomedic/logic/parser/listcommandparser/ListActivityParser.java
  src/main/java/gomedic/ui/CommandBox.java
  src/main/java/gomedic/ui/CommandHistory.java
  src/test/java/gomedic/logic/parser/listcommandparser/ListActivityParserTest.java
  src/test/java/gomedic/ui/CommandHistoryTest.java
Labels: hacktoberfest-accepted

#286 Clean find command, intro
  docs/UserGuide.md
Labels: hacktoberfest-accepted

#287 Bug fixes for help and UG
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/gomedic/commons/core/Messages.java
Labels: hacktoberfest-accepted

#288 Fix bug that editing an appointment would change it to activity
  src/main/java/gomedic/logic/commands/editcommand/EditActivityCommand.java
Labels: hacktoberfest-accepted

#290 Do bug fixes
  docs/UserGuide.md
  docs/images/patientug/tut_delete_patient_1.png
  docs/images/patientug/tut_delete_patient_2.png
  docs/images/patientug/tut_delete_patient_error.png
  docs/images/patientug/tut_edit_patient_1.png
  docs/images/patientug/tut_edit_patient_2.png
  docs/images/patientug/tut_edit_patient_error.png
  docs/images/patientug/tut_patient_1.png
  docs/images/patientug/tut_patient_2.png
  docs/images/patientug/tut_patient_error.png
  docs/images/patientug/tut_patientlist_1.png
  docs/images/patientug/tut_patientlist_2.png
  docs/images/patientug/tut_view_patient_1.png
  docs/images/patientug/tut_view_patient_2.png
  src/main/java/gomedic/model/person/patient/BloodType.java
  src/main/java/gomedic/ui/view/PatientView.java
Labels: hacktoberfest-accepted

#291 Resolves different date being shown bug when date is invalid
  src/main/java/gomedic/model/commonfield/Time.java
  src/test/java/gomedic/commons/core/ConfigTest.java
  src/test/java/gomedic/model/commonfield/TimeTest.java
Labels: hacktoberfest-accepted

#289 Fix addressbook data path, put all configs into data
  src/main/java/gomedic/MainApp.java
  src/main/java/gomedic/commons/core/Config.java
  src/main/java/gomedic/commons/core/LogsCenter.java
  src/test/java/gomedic/commons/core/ConfigTest.java
Labels: type.Bug

#294 Lauwsj/docu bug
  docs/UserGuide.md
Labels: type.Bug
